runtime: go
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  name: default

#[START env_variables]
env_variables:
  GOOGLE_CLOUD_PROJECT: gcp-ce-211411
  PUBSUB_VERIFICATION_TOKEN: ABCDEFGHIJKLMN123456789
  REDISHOST: '127.0.0.1'
  REDISPORT: '6379'
#[END env_variables]