runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  name: default

#[START env_variables]
env_variables:
  PUBSUB_VERIFICATION_TOKEN: ABCDEFGHIJKLMN123456789
  REDISHOST: '10.0.0.3'
  REDISPORT: '6379'
#[END env_variables]